import { defineSlotRecipe } from '@chakra-ui/react';

export const dropdownRecipe = defineSlotRecipe({
  slots: [
    'root',
    'labelContainer',
    'labelRow',
    'label',
    'required',
    'optional',
    'labelSubtext',
    'trigger',
    'triggerIcon',
    'triggerText',
    'triggerIndicator',
    'triggerTagsContainer',
    'triggerTag',
    'triggerTagLabel',
    'triggerTagClose',
    'triggerOverflowTag',
    'triggerOverflowTagLabel',
    'triggerOverflowTagClose',
    'content',
    'searchContainer',
    'searchIcon',
    'searchInput',
    'selectAllRow',
    'selectAllLabel',
    'separator',
    'itemList',
    'item',
    'itemIcon',
    'itemText',
    'itemCheckIcon',
    'emptyState',
    'errorContainer',
    'errorIcon',
    'errorText',
    'helperText',
    'loadingText',
    'mobileSearchContainer',
    'mobileSearchIcon',
    'mobileSearchInput',
    'mobileTagsRow',
    'mobileTag',
    'mobileTagLabel',
    'mobileTagClose',
    'mobileItemList',
    'mobileItem',
    'mobileItemText',
  ],
  className: 'dropdown',
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      width: '100%',
    },
    labelContainer: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
    },
    labelRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
    },
    label: {
      fontFamily: 'heading',
      fontWeight: 'medium',
      fontSize: '16px',
      lineHeight: '24px',
      color: 'navyGray.700',
    },
    required: {
      fontFamily: 'heading',
      fontWeight: 'medium',
      fontSize: '16px',
      lineHeight: '24px',
      color: 'red.200',
    },
    optional: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '12px',
      lineHeight: '18px',
      color: 'gray.400',
    },
    labelSubtext: {
      fontFamily: 'heading',
      fontWeight: 'medium',
      fontSize: '12px',
      lineHeight: '18px',
      color: 'gray.600',
    },
    trigger: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      height: '40px',
      paddingX: '12px',
      paddingY: '8px',
      backgroundColor: 'base.white',
      border: '1px solid',
      borderColor: 'gray.200',
      borderRadius: '12px',
      width: '100%',
      cursor: 'pointer',
      transition: 'all 0.2s',
      outline: 'none',
      _hover: {
        border: '1px solid',
        borderColor: 'successGreen.200',
      },
      _focus: {
        border: '1px solid',
        borderColor: 'navyGray.300',
      },
      _focusVisible: {
        border: '2px solid',
        borderColor: 'navyGray.300',
      },
      _disabled: {
        opacity: 0.6,
        cursor: 'not-allowed',
      },
    },
    triggerIcon: {
      width: '24px',
      height: '24px',
      flexShrink: 0,
      color: 'navyGray.700',
    },
    triggerText: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'navyGray.700',
      flex: 1,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      textAlign: 'left',
    },
    triggerIndicator: {
      width: '24px',
      height: '24px',
      flexShrink: 0,
      color: 'navyGray.700',
      transition: 'transform 0.2s',
    },
    triggerTagsContainer: {
      display: 'flex',
      flex: 1,
      gap: '4px',
      alignItems: 'center',
      overflow: 'hidden',
    },
    triggerTag: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      height: '24px',
      paddingX: '8px',
      paddingY: '4px',
      backgroundColor: 'green.50',
      borderRadius: '100px',
      flexShrink: 0,
    },
    triggerTagLabel: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '12px',
      lineHeight: '18px',
      color: 'successGreen.400',
      whiteSpace: 'nowrap',
    },
    triggerTagClose: {
      width: '16px',
      height: '16px',
      cursor: 'pointer',
      color: 'successGreen.400',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      _hover: {
        opacity: 0.7,
      },
    },
    triggerOverflowTag: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      height: '24px',
      paddingX: '8px',
      paddingY: '4px',
      backgroundColor: 'green.200',
      borderRadius: '100px',
      flexShrink: 0,
    },
    triggerOverflowTagLabel: {
      fontFamily: 'body',
      fontWeight: 'medium',
      fontSize: '12px',
      lineHeight: '18px',
      color: 'base.white',
      whiteSpace: 'nowrap',
    },
    triggerOverflowTagClose: {
      width: '16px',
      height: '16px',
      cursor: 'pointer',
      color: 'base.white',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      _hover: {
        opacity: 0.7,
      },
    },
    content: {
      backgroundColor: 'base.white',
      borderRadius: '8px',
      padding: '12px',
      boxShadow:
        '0px 0px 1px 0px rgba(24, 24, 27, 0.3), 0px 4px 8px 0px rgba(24, 24, 27, 0.1)',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      maxHeight: '400px',
      overflowY: 'auto',
      marginTop: '8px',
      minW:'280px'
    },
    searchContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      height: '40px',
      paddingX: '12px',
      paddingY: '8px',
      backgroundColor: 'base.white',
      border: '1px solid',
      borderColor: 'gray.200',
      borderRadius: '12px',
      flexShrink: 0,
      _focusWithin: {
        borderColor: 'navyGray.300',
      },
    },
    searchIcon: {
      width: '24px',
      height: '24px',
      flexShrink: 0,
      color: 'gray.400',
    },
    searchInput: {
      width: '100%',
      border: 'none',
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'navyGray.700',
      backgroundColor: 'transparent',
      outline: 'none',
      _placeholder: {
        color: 'gray.400',
      },
    },
    selectAllRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      height: '64px',
      paddingX: '12px',
      paddingY: '16px',
      backgroundColor: 'base.white',
      borderBottom: '1px solid',
      borderColor: 'gray.200',
      cursor: 'pointer',
      flexShrink: 0,
    },
    selectAllLabel: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'navyGray.700',
    },
    separator: {
      height: '1px',
      backgroundColor: 'gray.200',
    },
    itemList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      overflowY: 'auto',
    },
    item: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      paddingX: '4px',
      paddingY: '8px',
      borderRadius: '8px',
      cursor: 'pointer',
      transition: 'background 0.15s',
      _hover: {
        backgroundColor: 'gray.50',
      },
    },
    itemIcon: {
      width: '16px',
      height: '16px',
      flexShrink: 0,
      color: 'navyGray.700',
    },
    itemText: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'navyGray.700',
      flex: 1,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    itemCheckIcon: {
      width: '20px',
      height: '20px',
      flexShrink: 0,
      color: 'green.200',
    },
    emptyState: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'gray.400',
      padding: '8px 4px',
      textAlign: 'center',
    },
    errorContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
    },
    errorIcon: {
      width: '16px',
      height: '16px',
      flexShrink: 0,
      color: 'red.200',
    },
    errorText: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '12px',
      lineHeight: '18px',
      color: 'red.200',
    },
    helperText: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '12px',
      lineHeight: '18px',
      color: 'gray.600',
    },
    loadingText: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'gray.400',
      padding: '8px 4px',
      textAlign: 'center',
    },
    mobileSearchContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      height: '40px',
      paddingX: '12px',
      paddingY: '8px',
      backgroundColor: 'base.white',
      border: '1px solid',
      borderColor: 'gray.200',
      borderRadius: '12px',
      flexShrink: 0,
      _focusWithin: {
        borderColor: 'navyGray.300',
      },
    },
    mobileSearchIcon: {
      width: '16px',
      height: '16px',
      flexShrink: 0,
      color: 'navyGray.700',
    },
    mobileSearchInput: {
      width: '100%',
      border: 'none',
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'navyGray.700',
      backgroundColor: 'transparent',
      outline: 'none',
      _placeholder: {
        color: 'gray.400',
      },
    },
    mobileTagsRow: {
      display: 'flex',
      gap: '4px',
      alignItems: 'center',
      overflow: 'hidden',
      flexShrink: 0,
    },
    mobileTag: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      height: '32px',
      paddingX: '12px',
      paddingY: '8px',
      backgroundColor: 'green.50',
      borderRadius: '100px',
      flexShrink: 0,
    },
    mobileTagLabel: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'successGreen.400',
      whiteSpace: 'nowrap',
    },
    mobileTagClose: {
      width: '24px',
      height: '24px',
      cursor: 'pointer',
      color: 'successGreen.400',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    mobileItemList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
      overflowY: 'auto',
      flex: 1,
    },
    mobileItem: {
      display: 'flex',
      alignItems: 'center',
      height: '48px',
      padding: '8px',
      borderRadius: '12px',
      cursor: 'pointer',
      transition: 'background 0.15s',
      flexShrink: 0,
    },
    mobileItemText: {
      fontFamily: 'body',
      fontWeight: 'regular',
      fontSize: '14px',
      lineHeight: '20px',
      color: 'navyGray.700',
      flex: 1,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
  },
  variants: {
    size: {
      md: {
        trigger: {
          height: '40px',
        },
      },
      lg: {
        trigger: {
          height: '48px',
        },
      },
    },
    isOpen: {
      true: {
        triggerIndicator: {
          transform: 'rotate(180deg)',
        },
      },
    },
    isError: {
      true: {
        trigger: {
          borderColor: 'red.200',
          backgroundColor: 'red.50',
        },
      },
    },
    isFocused: {
      true: {
        trigger: {
          borderColor: 'navyGray.300',
        },
      },
    },
  },
  compoundVariants: [
    {
      isError: true,
      isFocused: true,
      css: {
        trigger: {
          borderColor: 'red.200',
          backgroundColor: 'red.50',
        },
      },
    },
  ],
  defaultVariants: {
    size: 'md',
  },
});
