name: PROD Master Workflow

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write
  issues: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'release' && github.event.release.target_commitish == 'master'}}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: ${{ github.repository }}
  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Install node dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
    
    - name: Build package
      run: npm run build:lib
    
    - name: Build Storybook
      run: npm run build-storybook
    
    - name: Get latest tag and bump patch
      id: version
      run: |
        git fetch --tags

        TAG="${{ github.event.release.tag_name }}"

        FINAL_VERSION=${TAG#v}
        echo "VERSION=$FINAL_VERSION" >> $GITHUB_ENV
        echo "Publishing version: $FINAL_VERSION"
    
    - name: Publish to GitHub Packages
      run: |
        npm version --no-git-tag-version ${VERSION}
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    
    - name: Upload Storybook to S3
      run: |
        aws s3 sync storybook-static/ s3://${{ vars.STORYBOOK_BUCKET }}/storybook/${{ github.event.release.tag_name }}/
        aws s3 rm s3://${{ vars.STORYBOOK_BUCKET }}/storybook/latest/ --recursive
        aws s3 sync storybook-static/ s3://${{ vars.STORYBOOK_BUCKET }}/storybook/latest/
